# Generated by Django 2.1.3 on 2018-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItemPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=255, verbose_name='店名')),
                ('item', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='価格')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='商品名')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('shop', models.CharField(max_length=255, verbose_name='店名')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='価格')),
            ],
        ),
    ]
